# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 082e50c29e574a236cf05ff4f765eaa5afbb2f30f6c33dd4fe7633b8fb590232209eed1b0243702730f0f2b30a1a3ecc05ab9400e67b22985b6c8b8d73a9c87d

test:
  secret_key_base: 259dad0ad28ded84b0071d61be60c5634c80afbef8cf585ae619352f1964e6d0f3bd803527131171a1c4bc0165496b3eeed1a1cfccbdb21a28971f2a9b2407d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
